palette = "catppuccin_mocha"

format = """
[](yellow)\
$directory\
[](fg:yellow bg:mauve)\
$git_branch\
$git_status\
[](fg:mauve bg:red)\
$c\
$nodejs\
$rust\
[ ](fg:red)\
"""

[os]
style = "bg:#9A348E"
disabled = false

[os.symbols]
EndeavourOS = " 󰣇  "

[directory]
style = "bg:yellow fg:base bold"
format = "[ $path ]($style)"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:mauve fg:base bold"
format = '[ $symbol ](bg:mauve fg:base)[$branch ]($style)'

[git_status]
style = "bg:mauve fg:base bold"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:red fg:base bold"
format = '[ $symbol ](bg:red fg:base bold)[NodeJS $version ]($style)'

[rust]
symbol = ""
style = "bg:red fg:base bold"
format = '[ $symbol ](bg:red fg:base bold)[Rust $version ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
